import { K, Schema, SparseVectorIndexConfig } from "chromadb";
import { ChromaBm25EmbeddingFunction } from "@chroma-core/chroma-bm25";

export const COLLECTION_NAME = "reebot-hybrid-v1";
export const SPARSE_INDEX_KEY = "bm25_embedding";

const schema = new Schema().createIndex(
  new SparseVectorIndexConfig({
    sourceKey: K.DOCUMENT,
    embeddingFunction: new ChromaBm25EmbeddingFunction(),
    bm25: true,
  }),
  SPARSE_INDEX_KEY,
);

let collectionPromise;

export function getReebotCollection(chroma) {
  if (!collectionPromise) {
    collectionPromise = chroma
      .getOrCreateCollection({
        name: COLLECTION_NAME,
        schema,
        // Dense vectors are generated by OpenAI and supplied during ingestion.
        embeddingFunction: null,
      })
      .catch((error) => {
        collectionPromise = undefined;
        throw error;
      });
  }
  return collectionPromise;
}
